(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | ref'mk : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments ref'mk {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | ref'mk x => x
  end.

(* Why3 goal *)
Theorem lemma_divisor_mult'vc :
  forall (d:Numbers.BinNums.Z), forall (q:Numbers.BinNums.Z),
  forall (p:Numbers.BinNums.Z), ~ (d = 0%Z) ->
  ((ZArith.BinInt.Z.rem q d) = 0%Z) ->
  ((ZArith.BinInt.Z.rem (p * q)%Z d) = 0%Z).
Proof.
  intros d q p Hd Hrem.
  rewrite Z.mul_rem, Hrem, Z.mul_0_r; auto with zarith.
Qed.

